# DNS servers are only accepted as socket addresses
# If port is not specified default DNS :53 port will be used
dns = [
    "8.8.8.8",
    "8.8.4.4",
]

# How many queries to perform per second
queries_per_second = 2000

# Times to retry on connection timeout
retry = 5