# DNS servers are only accepted as socket addresses
# If port is not specified default DNS :53 port will be used
[[dns]]
addr = "8.8.8.8"
qps = 500

[[dns]]
addr = "8.8.8.4"
qps = 500

[[dns]]
addr = "77.88.8.8"
qps = 500

[[dns]]
addr = "77.88.8.1:53"
qps = 500

# Times to retry on connection timeout
retry = 5