[package]
name = "batch_resolve_cli"
version = "0.1.0"
authors = ["Mike Lubinets <lubinetsm@yandex.ru>"]

[[bin]]
name = "batch_resolve"

[dependencies]
futures = "0.1.11"
trust-dns = "0.10"
tokio-core = "0.1.6"
log = "0.3.7"
env_logger = "0.4.2"
lazy_static = "0.2"
clap = "2.21.2"