[package]
name = "rkn_resolver"
version = "0.1.0"
authors = ["Mike Lubinets <lubinetsm@yandex.ru>"]

[dependencies]
futures = "*"
futures-cpupool = "*"
trust-dns = "0.10"
tokio-core = "*"
log = "*"
env_logger = "*"